# Generated by Django 4.2 on 2024-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Is Moderator'),
        ),
    ]
