# Generated by Django 4.2 on 2025-01-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('author', models.CharField(max_length=100, verbose_name='Nom de l’écrivain')),
                ('description', models.TextField()),
                ('favorites', models.IntegerField(blank=True)),
                ('image_1', models.ImageField(upload_to='blog_images/', verbose_name='Image de coverture ')),
                ('image_2', models.ImageField(upload_to='blog_images/', verbose_name='Image de blog')),
                ('full_text', models.TextField()),
                ('date', models.DateField()),
                ('range', models.IntegerField(default='1')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('view', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'category Cours',
            },
        ),
        migrations.CreateModel(
            name='CategoryVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'category vlogs',
            },
        ),
        migrations.CreateModel(
            name='CategoryWorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'category workshops',
            },
        ),
        migrations.CreateModel(
            name='CoursePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses_planning/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'biopilates Course Planning',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('range', models.IntegerField(default='1')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='FinancerFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='financer_formation_images/')),
                ('pdf_financer_formation', models.FileField(blank=True, null=True, upload_to='financer_formation_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'biopilates financer votre formation',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Manuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='formation_extrnal_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'biopilates Manuel',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': ' Tages',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(verbose_name='Prénom et Nom')),
                ('image', models.ImageField(upload_to='teacher_images/')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nomber_phone', models.IntegerField(verbose_name='numéro téléphone')),
                ('specialite', models.CharField(verbose_name='spécialité')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teaches',
            },
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workshop_images/')),
                ('pdf_workshop', models.FileField(blank=True, null=True, upload_to='workshop_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='biopilate.categoryworkshop')),
            ],
            options={
                'verbose_name_plural': 'biopilates WorkShops',
            },
        ),
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='vlogs_images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='biopilate.categoryvlog')),
            ],
            options={
                'verbose_name_plural': 'biopilates vlogs',
            },
        ),
        migrations.CreateModel(
            name='SessionPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopilate.courseplanning')),
            ],
            options={
                'verbose_name_plural': 'biopilates Session Planning',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('full_text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructeur', to='biopilate.teaches')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('duree', models.CharField(blank=True, max_length=255, null=True, verbose_name='durée ')),
                ('description', models.TextField(blank=True, null=True)),
                ('range', models.IntegerField(default='1')),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='biopilate.category')),
            ],
            options={
                'verbose_name_plural': 'Plannings',
            },
        ),
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='biopilate.formation')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopilate.option')),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cours_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='biopilate.categorycours')),
                ('tages_cours', models.ManyToManyField(blank=True, related_name='tages_cours', to='biopilate.tages')),
            ],
            options={
                'verbose_name_plural': 'biopilates Cours',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biopilate.blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tages_blog',
            field=models.ManyToManyField(blank=True, related_name='tages_blog', to='biopilate.tages'),
        ),
    ]
