# Generated by Django 4.2 on 2024-06-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('author', models.CharField(max_length=100, verbose_name='Nom de l’écrivain')),
                ('description', models.TextField()),
                ('favorites', models.IntegerField()),
                ('image_1', models.ImageField(upload_to='blog_images/')),
                ('image_2', models.ImageField(upload_to='blog_images/')),
                ('full_text', models.TextField()),
                ('date', models.DateField()),
                ('range', models.IntegerField(default='1')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('range', models.IntegerField(default='1')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': ' Tages',
            },
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Titre')),
                ('price', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('validete', models.CharField(max_length=10, verbose_name='Validité ')),
            ],
            options={
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(verbose_name='Prénom et Nom')),
                ('image', models.ImageField(upload_to='teacher_images/')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nomber_phone', models.IntegerField(verbose_name='numéro téléphone')),
                ('specialite', models.CharField(verbose_name='spécialité')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teaches',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('full_text', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructeur', to='biopilate.teaches')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('range', models.IntegerField(default='1')),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='biopilate.category')),
            ],
            options={
                'verbose_name_plural': 'Plannings',
            },
        ),
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopilate.formation')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biopilate.option')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='options',
            field=models.ManyToManyField(through='biopilate.FormationCategory', to='biopilate.option'),
        ),
    ]
