# Generated by Django 4.2 on 2025-01-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplanning',
            old_name='course',
            new_name='course_id',
        ),
    ]
