# Generated by Django 4.2 on 2024-12-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Tarifs',
        ),
        migrations.AddField(
            model_name='blog',
            name='tages',
            field=models.ManyToManyField(blank=True, related_name='tages', to='biopilate.tages'),
        ),
        migrations.AddField(
            model_name='cours',
            name='tages',
            field=models.ManyToManyField(blank=True, related_name='tages', to='biopilate.tages'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_1',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Image de coverture '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_2',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Image de blog'),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biopilate.blog'),
        ),
    ]
