# Generated by Django 4.2 on 2024-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0002_categorycours_cours_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycours',
            options={'verbose_name_plural': 'category Cours'},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='options',
        ),
        migrations.RemoveField(
            model_name='formationcategory',
            name='status',
        ),
    ]
