# Generated by Django 4.2 on 2025-01-29 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0002_rename_course_sessionplanning_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionplanning',
            name='course_id',
        ),
        migrations.AddField(
            model_name='sessionplanning',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='biopilate.courseplanning', verbose_name='Related Course'),
            preserve_default=False,
        ),
    ]
