# Generated by Django 4.2 on 2024-06-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0002_planning_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
