# Generated by Django 4.2 on 2024-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0003_categoryvlog_vlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancerFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='financer_formation_images/')),
                ('pdf_financer_formation', models.FileField(blank=True, null=True, upload_to='financer_formation_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'biopilates financer votre formation',
            },
        ),
        migrations.CreateModel(
            name='Manuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='formation_extrnal_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'biopilates Manuel',
            },
        ),
    ]
