# Generated by Django 4.2 on 2025-01-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0003_remove_sessionplanning_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseplanning',
            name='decription_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
