# Generated by Django 4.2 on 2024-06-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0003_alter_planning_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.IntegerField(default='0'),
        ),
    ]
