# Generated by Django 4.2 on 2024-06-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0004_blog_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='favorites',
            field=models.IntegerField(blank=True),
        ),
    ]
