# Generated by Django 4.2 on 2024-12-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0004_financerformation_manuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='related_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_formations', to='biopilate.formation', verbose_name='Related Formation'),
        ),
    ]
