# Generated by Django 4.2 on 2025-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0004_courseplanning_decription_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplanning',
            name='decription_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseplanning',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
