# Generated by Django 4.2 on 2024-12-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0005_formation_related_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationcategory',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='biopilate.formation'),
        ),
    ]
