# Generated by Django 4.2 on 2025-01-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0005_alter_courseplanning_decription_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationBioPlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='formations/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='formations/pdfs/', verbose_name='Document PDF')),
            ],
            options={
                'verbose_name': 'Formation BioPlates',
                'verbose_name_plural': 'Formations BioPlates',
            },
        ),
        migrations.CreateModel(
            name='FormationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du niveau')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='biopilate.formationbioplates')),
            ],
            options={
                'verbose_name': 'Niveau de formation',
                'verbose_name_plural': 'Niveaux de formation',
            },
        ),
    ]
