# Generated by Django 4.2 on 2024-06-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0006_formation_option_formationcategory_formation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifs',
            name='title',
            field=models.CharField(default='1 Cours Duo', max_length=200),
        ),
    ]
