# Generated by Django 4.2 on 2025-01-31 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0006_formationbioplates_formationlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationbioplates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formationbioplates',
            name='status',
            field=models.CharField(choices=[('pending', 'Brouillon'), ('published', 'Publié')], default='pending', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='formationbioplates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
