# Generated by Django 4.2 on 2025-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0007_formationbioplates_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationbioplates',
            name='image',
            field=models.ImageField(upload_to='formations/'),
        ),
        migrations.AlterField(
            model_name='formationbioplates',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='formations/pdfs/'),
        ),
    ]
