# Generated by Django 4.2 on 2024-06-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0007_tarifs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cours_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de publication'), ('approved', 'Publiée')], default='pending', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'biopilates Cours',
            },
        ),
    ]
