# Generated by Django 4.2 on 2025-02-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopilate', '0009_alter_formationbioplates_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationbioplates',
            name='formation_line',
            field=models.CharField(default='https://forms.zohopublic.com/carolinebergerdefemynie1/form/RecueildesbesoinsInscription/formperma/X8ryqIG4D2mdyqQI-FiBnW9a1vwiN-y0HuQGnPGetaQ'),
        ),
        migrations.AlterField(
            model_name='formationbioplates',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié')], default='pending', max_length=10, verbose_name='Statut'),
        ),
    ]
